name: Default

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NCS_ROOT: "${{ github.workspace }}/ncs"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: nRF SDK Setup
        run: sudo scripts/setup-machine.sh

      - name: nRF SDK Setup
        run: scripts/setup-sdk.sh

      - name: Pull Dependencies
        run: |
          bash -x scripts/pull-cjson-lib.sh &&
          bash -x scripts/setup-iotc-c-lib.sh

      - name: Build the Basic Sample Project for avt9152
        run: |
          cd samples/iotc-basic &&
          ../../scripts/build-project-avt9152.sh

      - name: Build the Basic Sample Project
        run: |
          cd samples/iotc-basic &&
          ../../scripts/build-project.sh

      - name: Build the Sensors and GPS Sample
        env:
          NRF_SAMPLE_CPID: ${{ secrets.NRF_SAMPLE_CPID }}
          NRF_SAMPLE_ENV: ${{ secrets.NRF_SAMPLE_ENV }}
        run: |
          cd samples/iotc-sensors-gps &&
          ../../scripts/build-project.sh

      - name: Publish Sample Artifacts (for avt9152)
        uses: actions/upload-artifact@v2
        with:
          name: nrf-sample-avt9152
          path: |
            samples/iotc-basic/build_avt9152/zephyr/merged.hex
            samples/iotc-basic/build_avt9152/zephyr/app_signed.hex
            samples/iotc-basic/build_avt9152/zephyr/app_update.bin

      - name: Publish Sample Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nrf-sample
          path: |
            samples/iotc-basic/build/zephyr/merged.hex
            samples/iotc-basic/build/zephyr/app_signed.hex
            samples/iotc-basic/build/zephyr/app_update.bin

      - name: Publish GPS Sample Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nrf-gps-sample
          path: |
            samples/iotc-sensors-gps/build/zephyr/merged.hex
            samples/iotc-sensors-gps/build/zephyr/app_signed.hex
            samples/iotc-sensors-gps/build/zephyr/app_update.bin

